server {
    listen 80;
    server_name _;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Proxy para el Backend (API)
    location /api {
        proxy_pass https://control-asistencia-backend-s1u5.onrender.com/api;
        proxy_set_header Host control-asistencia-backend-s1u5.onrender.com;
        proxy_ssl_server_name on;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }

    # Proxy para las imágenes QR
    location /qr {
        proxy_pass https://control-asistencia-backend-s1u5.onrender.com/qr;
        proxy_set_header Host control-asistencia-backend-s1u5.onrender.com;
        proxy_ssl_server_name on;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}