spring.application.name=control-asistencia-backend

spring.profiles.active=${SPRING_PROFILE:dev}

# JWT
app.jwt.secret=${JWT_SECRET:clave-secreta-super-segura-para-desarrollo-cambiar-en-produccion-1234567890}
app.jwt.expiration=${JWT_EXPIRATION:86400000}

# URL base QR
app.qr.base-url=${APP_QR_BASE_URL:http://localhost}

# Usuario administrador
app.admin.username=${ADMIN_USERNAME:admin}
app.admin.password=${ADMIN_PASSWORD:admin}